"""Create a small editable v1-lite configuration scaffold for one Git repository."""

from __future__ import annotations

from pathlib import Path

from git_deploy.errors import ConfigError
from git_deploy.git import GitRepository


def initialize_project(project_root: Path, destination: Path | None = None) -> Path:
    """Create a non-secret config scaffold without connecting or guessing a server.

    Args:
        project_root: Current project directory expected to be a Git worktree.
        destination: Optional explicit TOML path; defaults to ``deploy.toml``.

    Returns:
        Path of the newly created configuration scaffold.
    """

    root = project_root.resolve()
    GitRepository(root).validate()
    path = (destination or root / "deploy.toml").expanduser().resolve()
    if path.exists():
        raise ConfigError(f"refusing to overwrite existing configuration: {path}")
    if path.parent != root:
        raise ConfigError("init configuration must be created in the Git project root")
    steps, outputs = _suggestions(root)
    step_lines = "\n".join(f'  "{step}",' for step in steps)
    output_blocks = "\n\n".join(
        f'[[outputs]]\nlocal = "{local}"\nremote = "{remote}"\ndelete_removed = true'
        for local, remote in outputs
    )
    content = f'''# Generated by git-deploy init. Review every value before the first dry-run.
default_target = "dev"

[source]
include = ["**"]
exclude = ["tests/**", "docs/**"]
require_clean_worktree = false

[build]
steps = [
{step_lines}
]
timeout = 900
'''
    if output_blocks:
        content += "\n" + output_blocks + "\n"
    content += '''
# Choose ONE target style and uncomment/edit it. Alias uses native OpenSSH.
# [targets.dev]
# protocol = "sftp"
# ssh_host_alias = "project-dev"
# remote_root = "/srv/project"

# [targets.dev]
# protocol = "ftp"
# host = "ftp.example.com"
# username = "deploy"
# password_env = "DEPLOY_FTP_PASSWORD"
# remote_root = "/public_html"
'''
    try:
        path.write_text(content, encoding="utf-8")
    except OSError as exc:
        raise ConfigError(f"cannot create configuration {path}: {exc}") from exc
    return path


def _suggestions(root: Path) -> tuple[tuple[str, ...], tuple[tuple[str, str], ...]]:
    """Return conservative build/output suggestions from common lock files."""

    steps: list[str] = []
    outputs: list[tuple[str, str]] = []
    if (root / "pnpm-lock.yaml").is_file():
        steps.extend(("pnpm install --frozen-lockfile", "pnpm run build"))
        outputs.append(("dist", "public/dist"))
    elif (root / "package-lock.json").is_file():
        steps.extend(("npm ci", "npm run build"))
        outputs.append(("dist", "public/dist"))
    elif (root / "yarn.lock").is_file():
        steps.extend(("yarn install --frozen-lockfile", "yarn build"))
        outputs.append(("dist", "public/dist"))
    if (root / "composer.lock").is_file():
        steps.append(
            "composer install --no-dev --prefer-dist --optimize-autoloader --no-interaction"
        )
        outputs.append(("vendor", "vendor"))
    return tuple(steps), tuple(outputs)
