"""UI-neutral application contracts shared by CLI and future TUI adapters."""

from .cancellation import (
    CancellationAction,
    CancellationState,
    CancellationStateMachine,
    CancellationTransition,
)
from .config_service import (
    ApplicationConfigService,
    ProjectSelection,
    SelectionState,
)
from .events import (
    ApplicationEvent,
    OperationEvent,
    OperationEventKind,
    OperationProgressEvent,
    OperationStartedEvent,
    OperationWarningEvent,
    TargetResolvedEvent,
    TerminalResultEvent,
    TransactionStage,
    TransactionStageEvent,
)
from .deploy_service import (
    ConfirmationGrant,
    DeployService,
)
from .doctor_service import (
    DoctorCheckCategory,
    DoctorCheckResult,
    DoctorCheckStatus,
    DoctorContextItem,
    DoctorRequest,
    DoctorResult,
    DoctorService,
)
from .doctor_checks import ProjectDoctorChecks, standard_doctor_service
from .history_service import (
    HistoryEntry,
    HistoryLineage,
    HistoryResult,
    HistoryService,
)
from .models import (
    ApplicationRequest,
    DeployRequest,
    GCRequest,
    HistoryRequest,
    OperationKind,
    OperationRequest,
    PlanRequest,
    RollbackRequest,
    SideEffectLevel,
    StateAction,
    StateRequest,
    VerifyRequest,
)
from .policy import (
    ConfirmationPolicy,
    ConfirmationRequirement,
    EnvironmentRisk,
    RiskFactor,
    RiskItem,
    RiskLevel,
    confirmation_policy_for,
)
from .plan_token import (
    OperationPlanToken,
    PlanTokenSigner,
    StalePlanError,
    confirmation_policy_fingerprint,
)
from .plan_service import (
    ArtifactMappingPlan,
    BuildPlanSummary,
    FrozenDomainFile,
    PlannedChange,
    RevisionPlanResult,
    RevisionSelectionOrigin,
    RevisionPlanService,
    to_frozen_source_diff_plan,
)
from .errors import (
    ApplicationError,
    ErrorCategory,
    ErrorContextItem,
    application_error_from_exception,
)
from .results import ApplicationResult, ResultField, ResultStatus
from .rollback_service import (
    LatestRollbackPlan,
    LatestRollbackService,
    RollbackPathPlan,
)
from .state_service import (
    OpenTransactionSummary,
    StateInspectResult,
    StateInspectService,
    StateVerifyMode,
    StateVerifyResult,
)
from .verify_service import (
    VerifyMode,
    VerifyPathResult,
    VerifyResult,
    VerifyService,
)
from .worker import (
    ApplicationWorker,
    DuplicateOperationError,
    TargetBusyError,
    WorkerHandle,
)

__all__ = [
    "ApplicationEvent",
    "ApplicationRequest",
    "ApplicationError",
    "ApplicationConfigService",
    "ApplicationResult",
    "ApplicationWorker",
    "ArtifactMappingPlan",
    "BuildPlanSummary",
    "CancellationAction",
    "CancellationState",
    "CancellationStateMachine",
    "CancellationTransition",
    "ConfirmationPolicy",
    "ConfirmationRequirement",
    "ConfirmationGrant",
    "DeployRequest",
    "DeployService",
    "DoctorCheckCategory",
    "DoctorCheckResult",
    "DoctorCheckStatus",
    "DoctorContextItem",
    "DoctorRequest",
    "DoctorResult",
    "DoctorService",
    "ProjectDoctorChecks",
    "DuplicateOperationError",
    "ErrorCategory",
    "ErrorContextItem",
    "EnvironmentRisk",
    "GCRequest",
    "HistoryRequest",
    "HistoryEntry",
    "HistoryLineage",
    "HistoryResult",
    "HistoryService",
    "LatestRollbackPlan",
    "LatestRollbackService",
    "OperationKind",
    "OperationPlanToken",
    "OperationEvent",
    "OperationEventKind",
    "OperationProgressEvent",
    "OperationRequest",
    "OperationStartedEvent",
    "OperationWarningEvent",
    "OpenTransactionSummary",
    "PlanRequest",
    "PlanTokenSigner",
    "PlannedChange",
    "FrozenDomainFile",
    "ProjectSelection",
    "ResultField",
    "ResultStatus",
    "RevisionPlanResult",
    "RevisionSelectionOrigin",
    "RevisionPlanService",
    "to_frozen_source_diff_plan",
    "RiskFactor",
    "RiskItem",
    "RiskLevel",
    "RollbackRequest",
    "RollbackPathPlan",
    "SideEffectLevel",
    "SelectionState",
    "StateAction",
    "StateInspectResult",
    "StateInspectService",
    "StateVerifyMode",
    "StateVerifyResult",
    "StalePlanError",
    "StateRequest",
    "TargetResolvedEvent",
    "TargetBusyError",
    "TerminalResultEvent",
    "TransactionStage",
    "TransactionStageEvent",
    "VerifyRequest",
    "VerifyMode",
    "VerifyPathResult",
    "VerifyResult",
    "VerifyService",
    "WorkerHandle",
    "application_error_from_exception",
    "confirmation_policy_for",
    "confirmation_policy_fingerprint",
    "standard_doctor_service",
]
